USE [master]
GO
/****** Object:  Database [Office]    Script Date: 05/26/2015 13:49:11 ******/
CREATE DATABASE [Office] ON  PRIMARY 
( NAME = N'Office', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Office.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Office_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Office_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Office] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Office].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Office] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Office] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Office] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Office] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Office] SET ARITHABORT OFF
GO
ALTER DATABASE [Office] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Office] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Office] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Office] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Office] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Office] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Office] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Office] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Office] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Office] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Office] SET  DISABLE_BROKER
GO
ALTER DATABASE [Office] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Office] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Office] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Office] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Office] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Office] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Office] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Office] SET  READ_WRITE
GO
ALTER DATABASE [Office] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Office] SET  MULTI_USER
GO
ALTER DATABASE [Office] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Office] SET DB_CHAINING OFF
GO
USE [Office]
GO
/****** Object:  Table [dbo].[GenID]    Script Date: 05/26/2015 13:49:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GenID](
	[tableName] [nvarchar](50) NOT NULL,
	[lastID] [int] NOT NULL,
 CONSTRAINT [PK_GenID] PRIMARY KEY CLUSTERED 
(
	[tableName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 05/26/2015 13:49:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[id] [int] NOT NULL,
	[fio] [nvarchar](100) NOT NULL,
	[chef] [int] NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[addUser]    Script Date: 05/26/2015 13:49:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[addUser] (@fio nvarchar(100),
					 @chefID int)
AS
DECLARE @id int;

SET @id = (SELECT lastID 
      	FROM GenID 
      	WHERE tableName = 'Employee');

IF @chefID = 0
	INSERT INTO Employee VALUES(@id, @fio, null); 
ELSE
	INSERT INTO Employee VALUES(@id, @fio, @chefID); 


UPDATE GenID
SET lastID = lastID + 1
WHERE tableName = 'Employee';
GO
/****** Object:  ForeignKey [FK_Employee_Employee]    Script Date: 05/26/2015 13:49:13 ******/
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_Employee] FOREIGN KEY([chef])
REFERENCES [dbo].[Employee] ([id])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_Employee]
GO
